# Generated by Django 3.2.15 on 2022-11-16 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 11, 16, 15, 53, 45, 903796, tzinfo=utc), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=300)),
                ('surname', models.CharField(default='no surname', max_length=300)),
                ('nationality', models.CharField(blank=True, max_length=300, null=True)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_application', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(default='no address added', max_length=300)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Starting'), (1, 'Processing'), (2, 'Finished'), (3, 'Canceled')], null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client/')),
                ('slug1', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 11, 16, 15, 53, 45, 904831, tzinfo=utc), max_length=40)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='District_City', to='viya1.city')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 11, 16, 15, 53, 45, 903796, tzinfo=utc), max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='viya1.city')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=300, null=True)),
                ('person_surname', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_offeraddress', to='viya1.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_offeraddress', to='viya1.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_offeraddress', to='viya1.division')),
            ],
        ),
        migrations.CreateModel(
            name='OfferCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_partner', models.IntegerField(choices=[(1, 'Present partner'), (2, 'Past partner')], default=0)),
                ('name_of_company', models.CharField(default='name of company', max_length=300)),
                ('year_of_establishment', models.CharField(default='year', max_length=300)),
                ('address', models.CharField(default='year', max_length=300)),
                ('phone_number', models.CharField(default='phone number', max_length=300)),
                ('number_of_project', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('website', models.CharField(default='link', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_offer', to='viya1.offeraddress')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viya1.emails')),
            ],
        ),
        migrations.CreateModel(
            name='OfferFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_feature', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=300)),
                ('status_of_project', models.IntegerField(blank=True, choices=[(1, 'completed'), (2, 'uncompleted')], null=True)),
                ('year_of_completion', models.CharField(max_length=300)),
                ('type_of_project', models.IntegerField(blank=True, choices=[(1, 'Villa Complex'), (2, 'Apartment Complex')], null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('website', models.CharField(default='link', max_length=100)),
                ('city_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OfferProject_City', to='viya1.city')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offercompany', to='viya1.offercompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_offerproject', to='viya1.contact')),
            ],
        ),
        migrations.CreateModel(
            name='OfferProjectPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_project', models.ImageField(blank=True, null=True, upload_to='offers/')),
            ],
        ),
        migrations.CreateModel(
            name='OfferProjectPlanPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_plan_project', models.ImageField(blank=True, null=True, upload_to='offers/')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRoomTypeExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_OfferAddress', to='viya1.offeraddress')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_offer', to='viya1.city')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_OfferCompany', to='viya1.offercompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_OfferContact', to='viya1.offercontact')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_District', to='viya1.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_Division', to='viya1.division')),
                ('features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_OfferFeatures', to='viya1.offerfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_partner', models.IntegerField(choices=[(1, 'Present partner'), (2, 'Past partner')], default=0)),
                ('name_of_company', models.CharField(default='name of company', max_length=300)),
                ('year_of_establishment', models.CharField(default='year', max_length=300)),
                ('address', models.CharField(default='year', max_length=300)),
                ('phone_number', models.CharField(default='phone number', max_length=300)),
                ('number_of_project', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('website', models.CharField(default='link', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=300, null=True)),
                ('person_surname', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(default='no title added', max_length=30)),
                ('name', models.CharField(default='no title added', max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('advert_no', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('advert_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('square_meter_brut', models.IntegerField(default=0)),
                ('square_meter_net', models.IntegerField(default=0)),
                ('nr_of_rooms', models.CharField(max_length=10)),
                ('nr_of_bathrooms', models.IntegerField(default=0)),
                ('nr_of_floors', models.IntegerField(default=0)),
                ('position_of_floor', models.IntegerField(default=0)),
                ('furniture', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('address', models.CharField(default='no address', max_length=300)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('sours', models.IntegerField(choices=[(0, 'Unknown'), (1, 'www.sahibinden.com'), (2, 'www.hepsiemlak.com'), (3, 'www.bankadan.com'), (4, 'Partner')], default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='viya1.city')),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='viya1.division')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_property', models.IntegerField(choices=[(0, 'Villa'), (1, 'Apartment'), (2, 'Shop'), (3, 'Land')], default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubDistrict_City', to='viya1.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='viya1.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubDistrict_Division', to='viya1.division')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_property', models.BooleanField(default=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property1', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='Sours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sours_of_ads', models.IntegerField(choices=[(0, 'Unknown'), (1, 'www.sahibinden.com'), (2, 'www.hepsiemlak.com'), (3, 'www.bankadan.com'), (4, 'Partner')], default=0)),
                ('sours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_sours', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='did not add seller name', max_length=100)),
                ('work_phone_nr', models.CharField(default='no work phone', max_length=100)),
                ('personal_phone_nr', models.CharField(default='no personal phone', max_length=100)),
                ('company_name', models.CharField(default='no company name', max_length=100)),
                ('status_of_property', models.IntegerField(choices=[(0, 'Sale'), (1, 'Sold'), (2, 'Resale'), (3, 'NoInfo')], default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_seller', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='ReferencesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Partner'), (2, 'Person'), (3, 'Hotel')], default=0)),
                ('reference_description', models.CharField(default='no reference', max_length=500)),
                ('reference_link', models.URLField(blank=True, max_length=500, null=True)),
                ('reference_phone_nr', models.CharField(default='no phone number added', max_length=500)),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_references_contact', to='viya1.client')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(default='no reference', max_length=500)),
                ('type_reference', models.IntegerField(choices=[(0, 'Other'), (1, 'Partner'), (2, 'Person'), (3, 'Hotel')], default=0)),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_references', to='viya1.client')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property/foto')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_p', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(default='name', max_length=300)),
                ('status_of_project', models.IntegerField(choices=[(1, 'completed'), (2, 'uncompleted')], default=0)),
                ('year_of_completion', models.CharField(default='year', max_length=300)),
                ('type_of_project', models.IntegerField(choices=[(1, 'Villa Complex'), (2, 'Apartment Complex')], default=0)),
                ('description', models.CharField(default='description', max_length=1000)),
                ('address', models.CharField(default='year', max_length=300)),
                ('phone_number', models.CharField(default='phone number', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('website', models.CharField(default='link', max_length=100)),
                ('project', models.ForeignKey(default='No company', on_delete=django.db.models.deletion.CASCADE, related_name='partner_project', to='viya1.partner')),
            ],
        ),
        migrations.CreateModel(
            name='OfferSqm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sqm', models.IntegerField(blank=True, null=True)),
                ('max_sqm', models.IntegerField(blank=True, null=True)),
                ('garden_meters', models.IntegerField(blank=True, null=True)),
                ('total_meters', models.IntegerField(blank=True, null=True)),
                ('sqm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sqm_offer', to='viya1.offers')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_type', to='viya1.offertype'),
        ),
        migrations.AddField(
            model_name='offers',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers_OfferProject', to='viya1.offerproject'),
        ),
        migrations.CreateModel(
            name='OfferPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_offer', to='viya1.offers')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerphotos_offers', to='viya1.offers')),
            ],
        ),
        migrations.CreateModel(
            name='OfferDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('extended_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_offer', to='viya1.offers')),
            ],
        ),
        migrations.AddField(
            model_name='offercontact',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viya1.phonenumber'),
        ),
        migrations.AddField(
            model_name='offeraddress',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_offer', to='viya1.subdistrict'),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_feature', models.CharField(default='feature name', max_length=300)),
                ('name_of_feature_Turkish', models.CharField(default='feature name', max_length=300)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_project', to='viya1.project')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=300)),
                ('surname', models.CharField(default='surname', max_length=300)),
                ('type_relationships', models.IntegerField(blank=True, choices=[(0, 'Husband'), (1, 'Wife'), (2, 'Child')], null=True)),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_members', to='viya1.client')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_document', models.CharField(default='name of document', max_length=300)),
                ('date_of_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='description of document', max_length=500)),
                ('family_dokument', models.FileField(blank=True, null=True, upload_to='client/documents/')),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_client', to='viya1.client')),
                ('family_member_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_member', to='viya1.familymember')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='viya1.division'),
        ),
        migrations.CreateModel(
            name='ClientDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_document', models.CharField(default='name of document', max_length=300)),
                ('description', models.CharField(default='description of document', max_length=500)),
                ('date_of_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_dokument', models.FileField(blank=True, null=True, upload_to='client/documents/')),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_documents', to='viya1.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(default='name', max_length=300)),
                ('phone_nr', models.CharField(default='phone number', max_length=300)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Personal'), (1, 'Company'), (2, 'Family')], null=True)),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_phone', to='viya1.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressOf', models.CharField(default=datetime.datetime(2022, 11, 16, 15, 53, 45, 905829, tzinfo=utc), max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_set', to='viya1.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_set', to='viya1.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_set', to='viya1.division')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdistrict_set', to='viya1.subdistrict')),
            ],
        ),
    ]
