# Generated by Django 3.2.5 on 2022-07-28 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressOf', models.CharField(default=datetime.datetime(2022, 7, 28, 5, 19, 30, 244489, tzinfo=utc), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 7, 28, 5, 19, 30, 243489, tzinfo=utc), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 7, 28, 5, 19, 30, 244489, tzinfo=utc), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 7, 28, 5, 19, 30, 244489, tzinfo=utc), max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='viya1.city')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_from_viya', models.CharField(default='no title added', max_length=30)),
                ('title_from_ads', models.CharField(default='no title added', max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('advert_no', models.IntegerField(default=0)),
                ('advert_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('square_meter', models.IntegerField(default=0)),
                ('nr_of_rooms', models.CharField(max_length=3)),
                ('nr_of_bathrooms', models.IntegerField(default=0)),
                ('nr_of_floors', models.IntegerField(default=0)),
                ('position_of_floor', models.IntegerField(default=0)),
                ('latitude', models.BooleanField(default=0.0)),
                ('longitude', models.BooleanField(default=0.0)),
                ('seller_name', models.CharField(default='name not added', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='viya1.address')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='viya1.city')),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='viya1.division')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_property', models.IntegerField(choices=[(0, 'Villa'), (1, 'Apartment'), (2, 'Shop'), (3, 'Land')], default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2022, 7, 28, 5, 19, 30, 244489, tzinfo=utc), max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='viya1.district')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_property', models.IntegerField(choices=[(0, 'Sale'), (1, 'Sold'), (2, 'Resale'), (3, 'NoInfo')], default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property1', to='viya1.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property/foto')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_p', to='viya1.property')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='viya1.division'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_set', to='viya1.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_set', to='viya1.district'),
        ),
        migrations.AddField(
            model_name='address',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_set', to='viya1.division'),
        ),
        migrations.AddField(
            model_name='address',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdistrict_set', to='viya1.subdistrict'),
        ),
    ]
