# Generated by Django 3.2.5 on 2022-07-28 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0002_auto_20220728_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='square_meter',
            new_name='square_meter_brut',
        ),
        migrations.RemoveField(
            model_name='property',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='property',
            name='furniture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meter_net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 19, 49, 991473, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 19, 49, 990437, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 19, 49, 991473, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 19, 49, 990437, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 19, 49, 991473, tzinfo=utc), max_length=20),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='did not add seller name', max_length=100)),
                ('work_phone_nr', models.CharField(default='no work phone', max_length=100)),
                ('personal_phone_nr', models.CharField(default='no personal phone', max_length=100)),
                ('company_name', models.CharField(default='no company name', max_length=100)),
                ('status_of_property', models.IntegerField(choices=[(0, 'Sale'), (1, 'Sold'), (2, 'Resale'), (3, 'NoInfo')], default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_seller', to='viya1.property')),
            ],
        ),
    ]
