# Generated by Django 3.2.5 on 2022-07-28 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0003_auto_20220728_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 24, 59, 670673, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 24, 59, 668674, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 24, 59, 669675, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 24, 59, 669675, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_of_property',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 24, 59, 669675, tzinfo=utc), max_length=20),
        ),
    ]
