# Generated by Django 3.2.5 on 2022-07-28 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0004_auto_20220728_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 37, 11, 140631, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 37, 11, 140631, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 37, 11, 140631, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 37, 11, 140631, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 11, 37, 11, 140631, tzinfo=utc), max_length=20),
        ),
        migrations.CreateModel(
            name='Sours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sours_of_ads', models.IntegerField(choices=[(0, 'Parner'), (1, 'www.sahibinden.com'), (2, 'www.hepsiemlak.com'), (3, 'Other')], default=0)),
                ('sours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_sours', to='viya1.property')),
            ],
        ),
    ]
