# Generated by Django 3.2.5 on 2022-07-28 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0006_auto_20220728_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 16, 43, 28, 731074, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 16, 43, 28, 729040, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 16, 43, 28, 730039, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 16, 43, 28, 730039, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 16, 43, 28, 730039, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='viya1.property'),
        ),
        migrations.DeleteModel(
            name='PropertySingle',
        ),
    ]
