# Generated by Django 3.2.5 on 2022-07-28 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0007_auto_20220728_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 19, 31, 59, 107466, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 19, 31, 59, 104351, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 19, 31, 59, 106467, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 19, 31, 59, 104351, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 28, 19, 31, 59, 106467, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='viya1.property'),
        ),
        migrations.CreateModel(
            name='PropertySingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property/foto')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_p', to='viya1.property')),
            ],
        ),
    ]
