# Generated by Django 3.2.5 on 2022-07-29 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0010_auto_20220729_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 29, 14, 540393, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 29, 14, 538390, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 29, 14, 539396, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 29, 14, 539396, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 29, 14, 540393, tzinfo=utc), max_length=20),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_property', models.IntegerField(choices=[(0, 'Sale'), (1, 'Sold'), (2, 'Resale'), (3, 'NoInfo')], default=0)),
                ('name_of_company', models.CharField(default='name of company', max_length=300)),
                ('year_of_establishment', models.CharField(default='year', max_length=300)),
                ('address', models.CharField(default='year', max_length=300)),
                ('phone_number', models.CharField(default='phone number', max_length=300)),
                ('number_of_project', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_partners', to='viya1.property')),
            ],
        ),
    ]
