# Generated by Django 3.2.5 on 2022-07-29 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0012_auto_20220729_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='status_of_property',
        ),
        migrations.AddField(
            model_name='partner',
            name='status_of_partner',
            field=models.IntegerField(choices=[(1, 'Present partner'), (2, 'Past partner')], default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 57, 55, 364608, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 57, 55, 359608, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 57, 55, 361612, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 57, 55, 360610, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 29, 7, 57, 55, 362609, tzinfo=utc), max_length=20),
        ),
    ]
