# Generated by Django 3.2.5 on 2022-07-31 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0018_auto_20220730_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status_of_offer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 22, 28, 14, 916154, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 22, 28, 14, 914115, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 22, 28, 14, 915117, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 22, 28, 14, 915117, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 22, 28, 14, 916154, tzinfo=utc), max_length=20),
        ),
    ]
