# Generated by Django 3.2.5 on 2022-08-01 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0019_auto_20220801_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title_from_ads',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title_from_viya',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 16, 48, 635332, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 16, 48, 633334, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 16, 48, 634332, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 16, 48, 634332, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 16, 48, 634332, tzinfo=utc), max_length=20),
        ),
    ]
