# Generated by Django 3.2.5 on 2022-08-01 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0020_auto_20220801_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address_full',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='status_of_offer',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 37, 26, 78379, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 37, 26, 76380, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 37, 26, 77380, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 37, 26, 77380, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 37, 26, 78379, tzinfo=utc), max_length=20),
        ),
    ]
