# Generated by Django 3.2.5 on 2022-08-01 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viya1', '0021_auto_20220801_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressOf',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 42, 2, 894608, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 42, 2, 892608, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 42, 2, 893609, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 42, 2, 893609, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='sours',
            field=models.IntegerField(choices=[(0, 'Zeray'), (1, 'www.sahibinden.com'), (2, 'www.hepsiemlak.com'), (3, 'https://www.bankadan.com/')], default=0),
        ),
        migrations.AlterField(
            model_name='sours',
            name='sours_of_ads',
            field=models.IntegerField(choices=[(0, 'Zeray'), (1, 'www.sahibinden.com'), (2, 'www.hepsiemlak.com'), (3, 'https://www.bankadan.com/')], default=0),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 8, 1, 13, 42, 2, 893609, tzinfo=utc), max_length=20),
        ),
    ]
